// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGeXt4YLTejy29UTyPnqKq_61E51ep_ng',
    appId: '1:285761296189:web:6c81c4fd19a1b1f0e25754',
    messagingSenderId: '285761296189',
    projectId: 'recipes-e32be',
    authDomain: 'recipes-e32be.firebaseapp.com',
    databaseURL: 'https://recipes-e32be-default-rtdb.firebaseio.com',
    storageBucket: 'recipes-e32be.appspot.com',
    measurementId: 'G-GKK7CXM35M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5uO4usbpLS7mun7MY9Xd4zqpV4M_j6_c',
    appId: '1:285761296189:android:18f9aeaa2c2ea24ce25754',
    messagingSenderId: '285761296189',
    projectId: 'recipes-e32be',
    databaseURL: 'https://recipes-e32be-default-rtdb.firebaseio.com',
    storageBucket: 'recipes-e32be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhWA9WFzE6EEE8gncA3IouluZthW7ErGo',
    appId: '1:285761296189:ios:668b0977247eba6ae25754',
    messagingSenderId: '285761296189',
    projectId: 'recipes-e32be',
    databaseURL: 'https://recipes-e32be-default-rtdb.firebaseio.com',
    storageBucket: 'recipes-e32be.appspot.com',
    iosClientId: '285761296189-a0jlto7m8nfu931v4tccco49g83es41s.apps.googleusercontent.com',
    iosBundleId: 'com.deam.recipe-app',
  );
}
